### ISSUE TITLE
Implement Questionnaire Generator in Clinical Site SSApp

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#144]
Each trial will have attached to it a questionnaire. The questionnaire is generated in the clinical-site-ssapp and then it is visible in the trial-participant-ssapp in the ediary section.

The questionnaire is accessible for the doctor from the Questionnaire menu item.
![image](https://user-images.githubusercontent.com/1469129/159005386-d31c801a-9d66-4bfb-96ec-8a2ed2dddf90.png)

Clicking on Questionnaire will navigate to a new page that holds the questions for current trial.
**PROM Questions**
![image](https://user-images.githubusercontent.com/1469129/159007312-46eeac3b-9511-4635-894a-539b2a1fc91b.png)

![image](https://user-images.githubusercontent.com/1469129/159007370-ba48ec81-3db7-4c0e-b8be-2cb9e43f5f83.png)

![image](https://user-images.githubusercontent.com/1469129/159007415-0bb3e3a8-7aea-41cc-b22c-a4dea69669c3.png)

**PREM Questions**
![image](https://user-images.githubusercontent.com/1469129/159008546-5bda5b90-4319-40eb-a3b4-59bd7f737b62.png)

![image](https://user-images.githubusercontent.com/1469129/159008606-545f86ff-5b9c-4676-8a52-d33676ed1d84.png)

![image](https://user-images.githubusercontent.com/1469129/159008641-70380878-3864-4ca6-80ca-d1169247093c.png)

PROM QUESTIONS/PREM QUESTIONS should be tabs
Answer Type (Checkbox | Slider | Free Text) should be a select html input(it could be a radio, but webcardinal cannot handle radios models right now).

All questions should be kept in a single DSU: questionnaire that should have the following structure:

```
{
prom:[
{
question: "Mobility", type:"slider", uid:"#generatedUID", minLabel:"No Mobility", maxLabel:"Normal mobility", steps:10
},
{
question: "Treatment", type:"checkbox", options:["Option 1","Option 2","Option 3"],uid:"#generatedUID"
},
{
question: "Usual Activiites", type:"free-text",uid:"#generatedUID"
}
],
prem:[...]
}
```
**DSU Logic**
This questionnaire DSU should be mounted in the clinical site wallet using the anchorId as mounting path. The sReadSSI of the questionnaire should be also stored in the site trial DSU. When SITE wants to change the questionnaire DSU, first will read the questionnaire sReadSSI from the trial and get the anchorId from that SSI. Having the anchorId will know from where to read/write in the questionnaireDSU.

**Trial-Participant-Notification**

A message tot all patients should be sent when a questionnaire DSU is updated/created. The message should contain
{
messageType:"QUESTIONNAIRE_UPDATE",
trialSSI:trialSreadSSI
}
*trialSreadSSI will be enough

**Comment by nliappas** [comment]
Remaining tasks: 

- a generator for uid's for each question
- messaging the questionnaire to patients enrolled in that trial
- set frequency page/modal (need to consult with business people or create a generic calendar frequency like outlook does, attached below to get ideas)
- revise the logic on the DSU and attach a trial number to the questionnaire object

![image](https://user-images.githubusercontent.com/67898132/161102716-b371e38d-a482-4a36-a875-e1c84f051bee.png)
