### ISSUE TITLE
[clinical-site-ssapp] Send devices DSU Identifiers to iot-adapter 

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#155]
1. use the approach presented in the #152
2. Implement add/delete/update 
 for add: use the sReadSSI
 for update use the entity uid(anchorId)
 for delete use the entity uid(anchorId) and unmountEntity
3. get rid of the DeviceService
`export default class DeviceService extends AbstractAPI {

    GET_DEVICE = `${this.ADAPTER_PATH}/resource/Device`;

    constructor(serverEndpoint) {
        super(serverEndpoint, 'iotAdapter');
    }

    getDeviceById(id, callback) {
        let path = this.GET_DEVICE + '/' + id;
        let headers = {};
        this.makeRequest('GET', path, headers, callback);
    }

    createDevice(data, callback) {
        let headers = {
            'Content-Type': 'application/json'
        };
        this.makeRequest('POST', this.GET_DEVICE, headers, data, callback);
    }

    searchDevice(callback) {
        let headers = {};
        this.makeRequest('GET', this.GET_DEVICE, headers, callback);
    }
} `

**Comment by nliappas** [comment]
Do we need to do edit and delete device in a trial? we need page+controller. @elubilu @nliappas @amedranogil

**Comment by Mastaleru** [comment]
completed a long time ago
