### ISSUE TITLE
SPONSOR:BUG - Submit without attachment

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#199]
I should not be able to submit without adding a  consent attachemnt
![image](https://user-images.githubusercontent.com/1469129/171588984-91f4b041-18ad-4478-8ea7-3f505e10e7c3.png)

**Comment by Mastaleru** [comment]
the same when adding the site consent
![image](https://user-images.githubusercontent.com/1469129/171592088-bf6dc689-e330-4f82-928b-863e38f40a0f.png)

**Comment by Desouler** [comment]
Completed
