### ISSUE TITLE
Add details why patient health data retrieval does not exists

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#202]
![image](https://user-images.githubusercontent.com/1469129/171632243-7b0ea2ff-c69e-42a5-9d0f-26b9465cd397.png)

**Comment by Mastaleru** [comment]
![image](https://user-images.githubusercontent.com/1469129/175928039-42c35c97-aded-4603-bf77-ec8204d24d8d.png)

**Comment by Mastaleru** [comment]
@elubilu, @raihan2006i, please find examples of how to use webcardinal here: https://webcardinal.github.io/webcardinal-workspace

**Comment by elubilu** [comment]
@Mastaleru  It should be on the done list, I think. Please check it. 

Thank you
