### ISSUE TITLE
Implement the TS Device Data

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#206]
Please prepare a page where the sponsor can visualise specific data per patient as in the mock-up. prepare the page to read the data from the adaptor based on permission 
![image](https://user-images.githubusercontent.com/58935926/171831360-9dc7da8a-4db9-4555-9ab5-2dc2a7ace087.png)

**Comment by Desouler** [comment]
disabled device button for now
