### ISSUE TITLE
Assign device

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#213]
When assigning a device to a patient  send message from iot adapter to the trial participant

**Comment by elubilu** [comment]
We are already doing it, 
Whenever we receive a device-assign request we collect observations and send them to the trial participant through messaging services. 

Is there anything else should I do?

**Comment by nliappas** [comment]
something like a notification I understand Ana means? that ok you are patient XX you have data available now?

**Comment by elubilu** [comment]
@nliappas  Perfect,
Thanks for the clarification.  I will do it through messaging services as well.

**Comment by Mastaleru** [comment]
when I click on the notification it redirects me to the HealthStuduies instead of Device Data

**Comment by Mastaleru** [comment]
@elubilu please check the above issue

**Comment by Mastaleru** [comment]
@elubilu why are you moving this to QA without start working on this task?

**Comment by elubilu** [comment]
I did work on it @Mastaleru

**Comment by elubilu** [comment]
Could you please pull common services and try again?

**Comment by Mastaleru** [comment]
I was using a user with an existing notification

**Comment by elubilu** [comment]
Thank you
Please don't be harsh to comment on anything.
