### ISSUE TITLE
Visualisation of patient data in Clinical site

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#215]
Please implement the view button (as in the mock up) and the corresponfing page so that the doctor can visualise the patient data the same way the patient is visualising in his wallet. 
![image](https://user-images.githubusercontent.com/58935926/174635401-47bb7949-1b88-4f35-89d0-72d840090c90.png)

**Comment by Mastaleru** [comment]
@elubilu I was unable to see the date in clinical site
![image](https://user-images.githubusercontent.com/1469129/178285186-cc5c962d-c544-4b3a-b682-9e0a059911fc.png)

while the date was visible in trial participant ssapp
![image](https://user-images.githubusercontent.com/1469129/178285332-c392f1de-29c2-4806-b58a-d9c4bab6ca91.png)

**Comment by elubilu** [comment]
This is different because we implemented this later. In the meantime you registered some devices.

**Comment by elubilu** [comment]
Can you please do the npm dev install and try again.

**Comment by Mastaleru** [comment]
fixed
