### ISSUE TITLE
[SPONSOR] Feedback modals improvements

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#225]
Now we have like this:

![image](https://user-images.githubusercontent.com/1469129/175540793-4b35bcef-a0c4-4115-bce6-c332124e64b1.png)

Remove Close button
Remove Maximize modal button

Add disableExpanding and disableCancelButton properties on the modal properties

![image](https://user-images.githubusercontent.com/1469129/175540494-414a20d0-9050-4803-aec8-8ae31ee69800.png)

**Comment by Desouler** [comment]
commited
