### ISSUE TITLE
Feedback navigation not properly working

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#227]
Going back from Feedback List to dashboard is redirecting user to Completed Studies.

![image](https://user-images.githubusercontent.com/1469129/175892149-7d7e651b-c7bf-4900-8e2e-60f46f6d67f9.png)

![image](https://user-images.githubusercontent.com/1469129/175892170-6b8598e7-0e8f-4899-a561-0e62f7c1fa16.png)

**Comment by Mastaleru** [comment]
@Ana-ui if we remove the Feedback from menu, only 5 items will remain on the landing page. We could put My Profile/My Permissions instead.

**Comment by cosmintuca** [comment]
As we discussed today, the landing page now looks like below. The notifications bell is shaking when we have notifications(@paiusCatalin 's improvement)
![image](https://user-images.githubusercontent.com/100202792/176883595-a912ea7d-980f-42b2-a530-af032864f3ab.png)

**Comment by Mastaleru** [comment]
invalid
