### ISSUE TITLE
Health Data Display: Not all the health data is displayed + various improvements 

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#239]
As a patient, I hold 3 different observations,but only the information from the first is visible.
![image](https://user-images.githubusercontent.com/1469129/176407979-1a65da4b-6488-46e1-9d44-815b8a4611c8.png)

I suggest to display all the available information among with useful information like the date when that particular health data was recorded.

Later on (subject of a separate task), useful graphs could be created in order to let the patient observe his health data evolution.
Examples: https://dribbble.com/shots/16559528-Vital

**Comment by Mastaleru** [comment]
@elubilu I was unable to see all the available information for the patient.

**Comment by elubilu** [comment]
Can you please explain, what are you expecting and the results?

**Comment by Mastaleru** [comment]
@elubilu I'm still not getting the desired data...and also you broke the "No data"

**Comment by Mastaleru** [comment]
![image](https://user-images.githubusercontent.com/1469129/178499166-d6a273c1-2bb2-4ccc-9067-9bc625cc6da2.png)
