### ISSUE TITLE
[Trial Participant] Redesign Landing page

### ISSUE THREAD

**Issue by paiusCatalin** [PharmaLedger-IMI/eco-iot-pmed-workspace#246]
1. Remove Feedback and Notifications from the displayed options for navigation - the result will have only 4 buttons, so increase a little bit the size and the icons not to have too many gaps
2. Add notification button on the top-right side of the profile picture, above and similar to the edit profile button.
3. It would be nice to have a bell shaking effect when there are active notifications.

Something similar, but should be adjusted to have a nice effect on the user experience:
```
img {
  animation: shake 1.0s;
  animation-iteration-count: infinite;
}

@keyframes shake {
  0% { transform: rotate(0deg); }
  25% { transform: rotate(20deg); }
  50% { transform: rotate(40deg); }
  75% { transform: rotate(-40deg); }
  100% { transform: rotate(-20deg); }
}
```

**Comment by cosmintuca** [comment]
https://github.com/PharmaLedger-IMI/eco-iot-pmed-workspace/issues/227#issuecomment-1172232876
