### ISSUE TITLE
[Clinical Site] Add the new patient statuses on the clinical site statistics like they were added on Sponsor SSApp

### ISSUE THREAD

**Issue by paiusCatalin** [PharmaLedger-IMI/eco-iot-pmed-workspace#247]
Statuses to add after the last status (Declined):

END_OF_TREATMENT: "End Of Treatment",
COMPLETED: "Completed",
DISCONTINUED: "Discontinued",
SCREEN_FAILED: "Screen Failed"

![image](https://user-images.githubusercontent.com/17168446/177268195-239914d6-d6af-403d-a2d4-ba6978b4272e.png)

**Comment by Mastaleru** [comment]
@Desouler check the enrollment percentage 

![image](https://user-images.githubusercontent.com/1469129/185894409-f8ffa700-fb97-4ad7-9bba-6e1feaf5673d.png)

**Comment by Desouler** [comment]
define enrollment percentage. Compared to what? Sum of all patients? Only patients that went through screening? Predefined number of patients needed for the trial?

**Comment by Mastaleru** [comment]
@Ana-ui

**Comment by Ana-ui** [comment]
Comapred with total number of the added patients
