### ISSUE TITLE
[Clinical Site] Update View Procedures page to Confirm Attendance and update the functionality

### ISSUE THREAD

**Issue by paiusCatalin** [PharmaLedger-IMI/eco-iot-pmed-workspace#248]
**Current State:**
On Visits page, View button is routing to View procedures page. On the View Procedures page, on the second column `(Status)`, a confirmation button can be pressed to check that the patient did the procedure.

**Update Requirement:** 
Change `"View"` button name to `"Confirm attendance"`.
Between first column and second column add another one, `Attendance`. For each row, add a dropdown with two options, `"Completed Investigation"`, `"Missed Investigation"`. The selected value will be displayed on the third column` (Status)`.
Update the DSU and (if needed) the DB after a value from the dropdown is selected.
_Add a window loader when the DSU operations are running._
_The design of the procedures list can remain as it is implemented at this moment._

**Reference mock-up, but to be modified according to the above specifications.**
![image](https://user-images.githubusercontent.com/17168446/177269879-0860f938-7f3c-4a88-a861-08b1f2969aca.png)

**Comment by Mastaleru** [comment]
completed
