### ISSUE TITLE
[Sponsor] Change the position of the 'add consent' button

### ISSUE THREAD

**Issue by anastath** [PharmaLedger-IMI/eco-iot-pmed-workspace#251]
In Sponsor App, Under page Trial/Trial ID/Consents → Please enlarge and center the text that says no consents available. Additionally, placing the button “Add Consent” closer to the center of the page would also be better UX. Please include the columns for the consent versions and then list no consents available when none are uploaded. The “Add Consent” button can then be placed at the top of the said table

**Comment by Desouler** [comment]
enlarge and center the text that says no consents available, for all such messages on the whole app.
I am not going to change the button placement for a particular page, as it is the theme of the whole app that needs to be changed. Need to discuss.
