### ISSUE TITLE
[Clinical Site] Fix the flow on how the TS status becomes  'Enrolled'

### ISSUE THREAD

**Issue by anastath** [PharmaLedger-IMI/eco-iot-pmed-workspace#254]
When the Site adds a TS number for the TS, the status of the Patient should automatically change from 'Screened' to 'Enrolled'. In the future, the button should be changed to 'Enroll the Patient'. Clicking on the button, will generate automatically the TS number and it will also change the Status of the Patient from 'Screened' to 'Enrolled'.

**Comment by Mastaleru** [comment]
Well, this is how it happens now. The TS number could not be automatically generated while the TS number is the sk key with the external hospital db.
