### ISSUE TITLE
[Clinical Site] Fix the 'Withdraw intention' status

### ISSUE THREAD

**Issue by anastath** [PharmaLedger-IMI/eco-iot-pmed-workspace#255]
If the TS clicks on ‘Withdraw Intention’ on a consent version, in the clinical site it appears as
Name: withdraw intention Status: withdrawn. Same if the TS clicks on ‘Withdraw’ Consent. We should have a different status for withdraw intention.
Also, a notification should be sent to the Clinical Site that the TS intends to withdraw a consent along with the reason provided by the TS.

**Comment by Mastaleru** [comment]
there are new tasks for handling patient statuses according with new business requirements.
