### ISSUE TITLE
Check the OUTDATED in the name of a new consent that was just added

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#257]
![image](https://user-images.githubusercontent.com/58935926/177736124-98e285ee-a730-4e6b-9dd5-56d8dc700294.png)

**Comment by Ana-ui** [comment]
When adding a new consent for the site - appears outdated in the name of the consent for a consent that was just added. please check and correct

**Comment by Mastaleru** [comment]
already fixed
