### ISSUE TITLE
Implement the Trial/Consent Page Identified BUG: Update the list of consent only with valid versions of the Consents

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#258]
It appears in main page two different versions of the same consent (which should be actually in the history page). It seams that it is missing one page. Please implement as in the mock up ![image](https://user-images.githubusercontent.com/58935926/177737925-b6c9ed9e-e6fc-482f-8484-5e734cad4892.png)
![image](https://user-images.githubusercontent.com/58935926/177738600-486129b8-6718-4daa-b9ab-72a3b43b44b0.png)

**Comment by Mastaleru** [comment]
all good
