### ISSUE TITLE
Preview Consent doesn't work

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#259]
Implement the visualisation of the consent as in the mockup 
![image](https://user-images.githubusercontent.com/58935926/177739328-451d3867-ca5f-4447-85ee-f1e4f725d7f0.png)
Remove the back button 
![image](https://user-images.githubusercontent.com/58935926/177739020-2846e026-b2a6-4259-8da2-eb47c0848ebc.png)

**Comment by Mastaleru** [comment]
note for @Mastaleru: it is working after refresh. check the dsu update
