### ISSUE TITLE
[SPO] [SITE] The button does not respond (Mac only)

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#271]
<img width="1245" alt="Screenshot 2022-07-17 at 5 43 38 PM" src="https://user-images.githubusercontent.com/77613409/179409331-e719643d-d624-4cd5-b7d4-1447d5e1c451.png">

<img width="1237" alt="Screenshot 2022-07-17 at 5 06 16 PM" src="https://user-images.githubusercontent.com/77613409/179409322-186cecb3-68e4-46c5-9186-b7f99edd1f0e.png">

**Comment by Mastaleru** [comment]
Rasel, you own a Mac, pleas test it:)

**Comment by elubilu** [comment]
@Mastaleru  it works for me.
