### ISSUE TITLE
[SITE] Showing set frequency of questionnaire to the user once selected/set

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#273]
<img width="915" alt="Screenshot 2022-07-17 at 5 33 32 PM" src="https://user-images.githubusercontent.com/77613409/179410989-07058721-267c-4c4d-b426-11f45e85598f.png">

EXAMPLE
<img width="348" alt="Screenshot 2022-07-17 at 6 18 26 PM" src="https://user-images.githubusercontent.com/77613409/179411029-c9dbc2de-1b3c-4c12-8bd2-70dfb0207ab4.png">

**Comment by Mastaleru** [comment]
@klivit, let's discuss this with UPM (@nliappas) in order to have an agreement here

**Comment by Mastaleru** [comment]
![image](https://user-images.githubusercontent.com/1469129/188895937-490e2a53-b242-4880-93e7-2a9985249986.png)
