### ISSUE TITLE
[SITE] Visits were never loaded (Mac only)

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#274]
<img width="1237" alt="Screenshot 2022-07-17 at 5 31 01 PM" src="https://user-images.githubusercontent.com/77613409/179411134-2d07abf3-ef95-40d6-8b05-44466902228c.png">

**Comment by Mastaleru** [comment]
did you added visits in sponsor?

**Comment by Mastaleru** [comment]
I will close this while the the visits will be added in the same time with the consent itself.
