### ISSUE TITLE
[SITE] Change of labels when adding subject details

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#278]
<img width="1240" alt="Screenshot 2022-07-17 at 8 09 37 PM" src="https://user-images.githubusercontent.com/77613409/179419813-afddc0ef-7c1e-4cdf-93af-a08f2c6da2d5.png">

**Comment by Mastaleru** [comment]
@elubilu let Name and Surname as it is, change only **Select your gender** and **Birth Date** labels
