### ISSUE TITLE
[RESEAR] Needs minor UI improvement (too tiny button)

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#280]
<img width="1239" alt="Screenshot 2022-07-17 at 8 41 32 PM" src="https://user-images.githubusercontent.com/77613409/179420158-50f167a2-5b44-4837-964c-d80096c07db3.png">

**Comment by Mastaleru** [comment]
@elubilu, let's disable button if not data is added to Title and text in order to prevent empty submissions. check also against whitespaces.
![image](https://user-images.githubusercontent.com/1469129/181002881-735f6a4c-7ca4-4874-984e-ed5d7deb02d8.png)

**Comment by Mastaleru** [comment]
@cosmintuca please also disable button, when the inputs are empty

**Comment by cosmintuca** [comment]
@Mastaleru  I forgot to add the issue number related to the commit so I'll paste the commit link here: https://github.com/PharmaLedger-IMI/eco-iot-pmed-workspace/commit/184f178224dbb621b0a625d48d10983bcee20dd6

**Comment by Mastaleru** [comment]
all good
