### ISSUE TITLE
[SPO] Recruitment period to be defined by Sponsor (NOT COMPLETED DESCRIPTION YET)

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#296]
![Screenshot 2022-07-22 at 6 07 37 PM 2](https://user-images.githubusercontent.com/77613409/180487960-67f7c667-6802-46b5-88cb-5c2d1838dcb4.png)

**Comment by klivit** [comment]
Similar issue is created after, issue #323

**Comment by paiusCatalin** [comment]
Removing of the Visits button will be treated within a separate task, after the visits are implemented per trial.
