### ISSUE TITLE
[SITE] Site does not define [master] recruitment period

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#297]
Associated issue: #296 

![Screenshot 2022-07-22 at 3 27 13 PM](https://user-images.githubusercontent.com/77613409/180488212-23b044aa-ddfc-4530-b479-3b733a356ed5.png)

**Comment by klivit** [comment]
Similar issue is created after (with some additional details), issue #325

**Comment by klivit** [comment]
<img width="745" alt="Screenshot 2022-08-03 at 1 08 54 PM" src="https://user-images.githubusercontent.com/77613409/182583150-1302e284-f1a1-4f34-bfdf-f9f34ad4d375.png">

**Comment by klivit** [comment]
@Mastaleru So, the SITET shall see the recruitment period defined by the SPO, but will not be able/expected to set ups any period inside of the master (as elaborated above).

**Comment by Mastaleru** [comment]
> site is added to the system/joins the trial (e.g., if rec. period. from 01/22 to 05/22, and the SITE joins 03/22, the rec.period. will be form 03/22).

The site is not joining the trial, the SITE is added to a trial by a sponsor. this is different thinking in terms of DSUs and decentralization.  For the moment we don't keep any date when the site is added to a trial. If you want this feature, please add it to a new task(label it as future), as it requires this change to be performed from the sponsor on each individual site

**Comment by klivit** [comment]
@Mastaleru (site is not joining the trial) = (added to a trial by a sponsor) It is just wording, which does not mean introducing new details. I agree that we can create a new issue for making the adjustment per site, but I strongly believe we can leave it as for the "future" task.
