### ISSUE TITLE
[SITE] No clear what "No action required" is intended to show on the Subjects page

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#298]
"No action required" does not change its status over the course of actions. For example, the patient signed consent, and as a Site, I have to sign it as well, but "No action required". What does this attribute intend to represent?

<img width="1226" alt="Screenshot 2022-07-22 at 8 05 43 PM" src="https://user-images.githubusercontent.com/77613409/180489480-a373cdf1-404c-4e95-8854-6b819cd747f7.png">

**Comment by Mastaleru** [comment]
duplicated of #270
