### ISSUE TITLE
[SITE] No visibility if the action has taken place or not

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#300]
Rescheduling procedure and confirming ("DONE") and ...

<img width="1294" alt="Screenshot 2022-07-22 at 8 39 03 PM" src="https://user-images.githubusercontent.com/77613409/180494781-a09c3db4-cc6a-4d4f-92a5-30073939d1bd.png">

... it is back to the same UI (e.g., like the change was not made). Question: Is it intended this way?

<img width="1292" alt="Screenshot 2022-07-22 at 8 39 13 PM" src="https://user-images.githubusercontent.com/77613409/180494793-de9532ff-8b64-41c2-96da-ee278876ac25.png">

**Comment by Mastaleru** [comment]
@klivit the date is updated in the table. I think that you tested an older version that was not auto updating.

**Comment by Mastaleru** [comment]
@cosmintuca let's add some feedback messages for each action on this page

**Comment by cosmintuca** [comment]
@Mastaleru I've added the changes! Please let me know if the next feedback messages are good: 
schedule new visit: '[visit name] have been scheduled! Wait for TP response!'
reschedule: ' [visit name] have been rescheduled! Wait for TP response!',
confirm: '[visit name] have been confirmed!'

**Comment by Mastaleru** [comment]
![image](https://user-images.githubusercontent.com/1469129/183953526-34d434f9-f535-435f-bfd7-dc533d50ffe4.png)
![image](https://user-images.githubusercontent.com/1469129/183954035-0e71eed4-6447-4b90-8d35-33b815db06c4.png)
![image](https://user-images.githubusercontent.com/1469129/183953674-d9a96ed8-0d04-43d2-8b2a-7fc9c173054e.png)
