### ISSUE TITLE
[TP] No visibility if the action has taken place or not 

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#301]
Similar issue: #300

After selecting a new date, the UI comes back with no visibility that action was made. Question: Shall we consider other statuses while pending for the other party (i.e., Site) to respond.

<img width="637" alt="Screenshot 2022-07-22 at 8 40 20 PM" src="https://user-images.githubusercontent.com/77613409/180497988-1c36a05b-e0f2-468c-a585-17c48540592c.png">

**Comment by Mastaleru** [comment]
@klivit , yes, SITE has to validate the rescheduled date
