### ISSUE TITLE
[TP] Questionnaire can be answered more than one time

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#303]
It shows as "pending" assessment, ...

<img width="386" alt="Screenshot 2022-07-22 at 9 18 41 PM" src="https://user-images.githubusercontent.com/77613409/180500249-aef7544a-cd27-4b45-8f04-d2489a394210.png">

... while it has been answered 3 times already.

<img width="1242" alt="Screenshot 2022-07-22 at 9 19 13 PM" src="https://user-images.githubusercontent.com/77613409/180500285-59879c24-62b9-40c1-b726-d8c451ba5e5c.png">

Once the Subject answered the assessment once, there shall be UI modifications.

<img width="387" alt="Screenshot 2022-07-22 at 9 22 34 PM" src="https://user-images.githubusercontent.com/77613409/180501207-e52a1140-8874-4541-8a8f-dfd65a79248c.png">

**Comment by Mastaleru** [comment]
the next answer will update the existing one for that day
