### ISSUE TITLE
[SPO] Rules for adding mandatory and optional consent

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#304]
<img width="1242" alt="Screenshot 2022-07-22 at 9 28 45 PM" src="https://user-images.githubusercontent.com/77613409/180513562-a884b51b-28e3-43d8-9f55-7b2a335bf88d.png">

Additional info: TP does not have to sign "Optional" consent to continue participation in the study. TP either can sign it (and then withdraw), decline, or just live in the list of consents (no action). Related issue (TP): #305

**Comment by klivit** [comment]
Adding more information as clarifying with the business:
- There should be **only one mandatory consent** per trial

**Comment by Mastaleru** [comment]
first consent should be mandatory and the rest optional. implement this by adding a business rule .e.g getAllowedNumberOfMandatoryConsents that for the moment will return a constant.
if there is no more than one choice the select should be disabled: so first consent will have Mandatory disabled, the next consents will have Optional and disabled.

**Comment by Desouler** [comment]
Commited

**Comment by Mastaleru** [comment]
When I'm trying to add a consent version
![image](https://user-images.githubusercontent.com/1469129/186181279-13a0ba1a-8f45-4d08-8cdc-9e05fff08e16.png)

**Comment by Mastaleru** [comment]
Please also change the modal name from New Consent to New Consent Version

**Comment by Desouler** [comment]
Commited @Mastaleru

**Comment by Mastaleru** [comment]
all good
