### ISSUE TITLE
[TP] Optional consent is not required

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#305]
A related issue with more elaborations: #304

Optional consent does not need to be mandatory signed. At this point, the user is given the information "Consent Required" in red colour, which is doubtful as it is perceived as I (as a TP) have to sign it.

<img width="399" alt="Screenshot 2022-07-22 at 10 58 07 PM" src="https://user-images.githubusercontent.com/77613409/180519013-2b1dfc2a-5d11-45b7-9ed3-cccfddf2cae4.png">

**We expect the TP to "answer" the request (either decline or accept).**

**Comment by klivit** [comment]
@Mastaleru Optional consents can be introduced to collect additional measurements/etc., let's say, to discover something new that was identified within the trial. If TP does not sign this [optional] consent, it will not affect TP's participation in the trial. So, with optional consent, we (as a SITE, SPO) can collect more info that might help us for some insights, but it is additional (in a sense, optional = additional but not necessary) and does not interfere with the course of a trial (for that kind of change, we would need a new version of mandatory consent).

If TP declines the optional consent, their participation in the study remains in any case. However, as was updated, TP needs to respond to the optional consent (decline or sign) -- if declines, TP goes as per mandatory consent; if signs, TP goes as per mandatory consent with additional procedures, etc. of optional consent.

Please let me know if more details are needed.

**Comment by Mastaleru** [comment]
@klivit thanks.

**Comment by Ana-ui** [comment]
It is required to consent but optional. It is clear from the UI, no need to modify it.
