### ISSUE TITLE
Study data is still visible even the participants revoked their consents/dynamic permissions.

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#306]
![image](https://user-images.githubusercontent.com/1469129/180959119-7baf3303-094d-41a1-9f97-b315dc966eb5.png)

Also, why the first 4 rows are doubled? 
The patient only has 4 records for SPO2
![image](https://user-images.githubusercontent.com/1469129/180960033-8185e503-ff28-492d-b685-4c268ca4304b.png)

**Comment by nliappas** [comment]
im keeping both arrays now.
