### ISSUE TITLE
[Site] Add Device - Implement fields validation 

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#309]
All fields are mandatory. Check against empty/whitespaces. 
Device Ids should be unique.
Save button should be disabled if the form has unfilled fields.

![image](https://user-images.githubusercontent.com/1469129/181506596-1ba68612-00e2-4cbf-b7f1-d2c41ee6fbf6.png)

**Comment by elubilu** [comment]
I can't change the status of the task. 
it should on Testing @Mastaleru
