### ISSUE TITLE
[SITE] Behavior check

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#315]
Follow the next steps on the development and blockchain deployment:

1. Create a new Sponsor account
2. Add Trial 1 -> Add one consent to this Trial 1
3. Add Trial 2 -> Add one consent to this Trial 2
4. Create new Site account -> Remain on dashboard-> Do not refresh it
5. Add Site to Trial 1 -> Add Site Trial 2 Consent 
6. Add Site to Trial 2 -> Add Site Trial 2 Consent 
7. Go to Site Dashboard ->E-Consent Trial Management
8. Check if both trials are there-> if not, check the console

Please don't refresh any of the actors during this testing procedure

Blockchain deployment: https://iot-upm.pharmaledger.dev/

Create accounts using custom prefixes: e.g. cosmin.tuca.sponsor1, cosmin.tuca.site1

**Comment by cosmintuca** [comment]
@Mastaleru  I followed the procedure you described above but it works as expected(both trials appear and no errors in console).
