### ISSUE TITLE
[SITE] Do not show the search bar if no patients are added to the trial

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#319]
![image](https://user-images.githubusercontent.com/1469129/182175649-60d75542-dcde-4784-aa82-5d1e33803dcf.png)

**Comment by Mastaleru** [comment]
I have 2 patients and I added a filter that does not match any of them. 
When the filtering is not matching any patient, all patients should be displayed.

![image](https://user-images.githubusercontent.com/1469129/182601091-674798dc-abd7-4989-adae-c1641baae296.png)

**Comment by cosmintuca** [comment]
@Mastaleru I made the changes in this commit : https://github.com/PharmaLedger-IMI/clinical-site-ssapp/commit/3d3a143056ded8080fb255392330a057d6ee5a1d
