### ISSUE TITLE
[Breadcrumb] Do not preserve messages in the intermediate segments

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#320]
I have the following message while I did not perform any action as my last navigation behavior.

![image](https://user-images.githubusercontent.com/1469129/182179456-cd2275f9-29d3-405a-8ab9-d1a33943a48e.png)

Steps to reproduce:

1. Go to patient devices.
2. Remove device assignation
3. **Now the message from the print screen appear and it is OK.**
4. Go to patient devices again.
5. Click on trial subjects from breadcrumb menu
6. **Now the message from the print screen appear and it is NOT OK.**

Proposed solution: in BreadcrumbNavigatorController
- cleanup the message if the segment is not the active/last one

**Comment by cosmintuca** [comment]
@Mastaleru I pushed the solution for this. Please check this commit: https://github.com/PharmaLedger-IMI/eco-iot-services/commit/9ebb639bbb38377fa5e8546ae179e9010f4a8a25

**Comment by Mastaleru** [comment]
@cosmintuca check my comment on your commit https://github.com/PharmaLedger-IMI/eco-iot-services/commit/9ebb639bbb38377fa5e8546ae179e9010f4a8a25#r80177631

**Comment by cosmintuca** [comment]
@Mastaleru I've made an update on the changes in this commit: https://github.com/PharmaLedger-IMI/eco-iot-services/commit/4d3e807a0689b827a288ef2605f31d9a5972efd8
