### ISSUE TITLE
Recruitment period per trial

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#323]
Please add the "Recruitment period" button instead of Visits Button which will be implemented per consent version. 
![image](https://user-images.githubusercontent.com/58935926/182570309-9159e613-4823-4797-9396-672a33b1ad23.png)

**Comment by klivit** [comment]
Duplicated, issue #296

**Comment by paiusCatalin** [comment]
Removing of the Visits button will be treated within a separate task, after the visits are implemented per trial.

**Comment by Mastaleru** [comment]
closing this. continuing with https://github.com/PharmaLedger-IMI/eco-iot-pmed-workspace/issues/365
