### ISSUE TITLE
Visits per consent version

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#324]
Move the Visits button from the trial page in the Consent page. the visits should be per version of consent 
![image](https://user-images.githubusercontent.com/58935926/182570884-607be4f3-2024-475e-bb9c-dfba8a4af75c.png)
![image](https://user-images.githubusercontent.com/58935926/182571087-428862a6-695e-4916-939d-2019ab5e88e3.png)

**Comment by klivit** [comment]
Duplicated, issue #295
