### ISSUE TITLE
Remove "Set Recruitment Period"  

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#325]
Modify the UI for Trial Subjects page by deleating the "set recruitment period" button. the recruitment period show be received as a message from the Sponsor and added as a subtitle of the page 
![image](https://user-images.githubusercontent.com/58935926/182579649-ac12273c-6e1f-4538-b603-7d676a41cb1d.png)

**Comment by klivit** [comment]
Duplicated (with some additional info), issue #297
