### ISSUE TITLE
[SITE] TP should be at least 18 yo

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#326]
![Screenshot 2022-07-29 at 1 35 26 PM](https://user-images.githubusercontent.com/77613409/182589045-3783635d-f12d-49a5-906a-16bc19086f09.png)

**Comment by Mastaleru** [comment]
@klivit any idea what will be the behavior for patients under 18?

**Comment by klivit** [comment]
@Mastaleru It remains as it would be under 14; we replace 14 with 18 (when you add a TP less 18 yo, the system will request 2 public DIDs of parents as it is already implemented).

**Comment by Mastaleru** [comment]
all good
