### ISSUE TITLE
Review patient status

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#327]
When a patient was added to the trial it status appears as enrolled which is not correct. 
![image](https://user-images.githubusercontent.com/58935926/182588536-7199968f-5ffb-4788-a234-08b9d15f96dd.png)
Please check the statuses and implement according with the table below. When a patient is added and no consent is signed the status should remain empty until the patient signes.
![image](https://user-images.githubusercontent.com/58935926/182588873-7d120b32-1502-468c-a057-27d487b21452.png)

**Comment by Mastaleru** [comment]
@klivit and @Ana-ui please give us some final tp status list.
@Ana-ui please also have a look here https://github.com/PharmaLedger-IMI/eco-iot-pmed-workspace/issues/330

**Comment by klivit** [comment]
Related issues (TP statuses): #329, #330

**Comment by klivit** [comment]
@Mastaleru @cosmintuca 

Manual = Manual by SITE

<img width="987" alt="Screenshot 2022-08-05 at 10 16 05 PM" src="https://user-images.githubusercontent.com/77613409/183145827-d3e6c4cb-529d-4972-bf01-0b132bf35d0c.png">

**Comment by klivit** [comment]
![image](https://user-images.githubusercontent.com/77613409/183147463-17dda27c-cc45-47f9-9792-9dfe65d31bf5.png)

**Comment by Mastaleru** [comment]
@klivit what does this mean ? the explanation in orange
![image](https://user-images.githubusercontent.com/1469129/183634069-196354d0-fbdf-4ec6-8380-df6a7b2bdcaf.png)

**Comment by klivit** [comment]
@Mastaleru "Enrolled", "Trial Conduct", and "In Treatment" can be considered synonyms. The preferred is "Enrolled", but in case you will hear from the business the other two, you might expect that it has the same meaning.

**Comment by Mastaleru** [comment]
Mockup ![image](https://user-images.githubusercontent.com/1469129/189720349-a87a65f3-d5fd-4e79-9788-f89ae18a1a48.png)

**Comment by Mastaleru** [comment]
Idea: To use a stepper progress bar with: Planned, Screened, Enrolled, In Treatment, Completed 

![image](https://user-images.githubusercontent.com/1469129/189721200-4857a2eb-d272-4acb-8bd6-f5d6aff26ce3.png)

Discontinued, Screen Failed and Withdrew will be illustrated with red

**Comment by cosmintuca** [comment]
https://github.com/PharmaLedger-IMI/clinical-site-ssapp
