### ISSUE TITLE
[TP] Signing, withdrawal, etc. consent procedure (step by step with modifications)

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#328]
TP receives a consent to be signed.

<img width="313" alt="Screenshot 2022-08-03 at 1 58 14 PM" src="https://user-images.githubusercontent.com/77613409/182597297-4c0ee20e-8220-4e0d-ab75-06f72ab570dd.png">

TP can sign the consent (electronically and manually).

<img width="311" alt="Screenshot 2022-08-03 at 1 58 24 PM" src="https://user-images.githubusercontent.com/77613409/182597412-803b5371-3b40-48f1-b64b-3bffd4f6562a.png">

<img width="305" alt="Screenshot 2022-08-03 at 2 00 10 PM" src="https://user-images.githubusercontent.com/77613409/182597439-6535c73d-5a8c-453c-a24c-cdde3ee335b4.png">

Once the consent is signed, the TP can request/inform of withdraw intention. 

-**CHANGE!!! "Withdraw Intention" -> "Withdraw"**-

<img width="310" alt="Screenshot 2022-08-03 at 2 19 30 PM" src="https://user-images.githubusercontent.com/77613409/182597645-7c363c1d-77bc-43ed-88f5-e1f92fb685b6.png">

**CHANGE!!! "Withdraw Intention" -> "Withdraw"**

<img width="312" alt="Screenshot 2022-08-03 at 2 24 46 PM" src="https://user-images.githubusercontent.com/77613409/182599690-d62dd5a6-7426-4329-9bdd-990dd89d173d.png">

**CHANGE!!! "withdraw-intention" -> "Withdraw"**

<img width="310" alt="Screenshot 2022-08-03 at 2 27 53 PM" src="https://user-images.githubusercontent.com/77613409/182601805-e921b1dd-8931-44a0-9591-1f08800bdf13.png">

As was mentioned, "complete" withdrawal of TP from the study can be done only by the SITE. Hence, this functionality should be gone as well as re-signing.

<img width="304" alt="Screenshot 2022-08-03 at 2 28 39 PM" src="https://user-images.githubusercontent.com/77613409/182602255-407e83c5-282f-4502-aba1-0154985e0016.png">

Assuming that UI for the consent part (i.e., view, sign, etc.) should be the same, we can consider having a list of "actions" (e.g., view, withdraw intention, etc.) with some of them to be muted based on the stage of the procedure.

**Comment by Mastaleru** [comment]
@cosmintuca Sign Manually should be disabled for the mock-trial

**Comment by klivit** [comment]
@Mastaleru It was confirmed by Baldwin, citing below:

"1. TP is the option to “Withdraw” only

2. Once “Withdraw” is selected, a notification is sent to the HCP/site to contact the TP about this decision. The TP status is changed to “Withdraw Intention” as it is currently designed. 

3. HCP should contact the TP to discuss the decision and confirm in the Clinical SIte App that the TP has withdrawn after the discussion. This will change the TP status to “Withdrawn” in all Apps."
