### ISSUE TITLE
[SITE] TP withdrawing process

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#329]
As mentioned in issue #328, SITE is the actor who will confirm/complete TP withdrawal. As shown below, the patient could withdraw themselves. We need to make the following change: TP -> withdraw intention, SITE -> withdrawal (after an in-person meeting with the TP and their final decision to withdraw). 

<img width="1206" alt="Screenshot 2022-08-03 at 3 16 25 PM" src="https://user-images.githubusercontent.com/77613409/182607694-df873885-e218-4dd9-b7c0-34bd711be5c9.png">

<img width="462" alt="182607722-daa85254-7b52-4ff8-8a06-bc2bca0b9d00" src="https://user-images.githubusercontent.com/77613409/182799173-8f17083d-f336-4567-9a70-499651952851.png">

**Comment by klivit** [comment]
Related issue (TP status): #330

**Comment by Ana-ui** [comment]
Step1: When TP clicks "Withdraw Intention" button the TS status should be changed to "Withdraw intention" and Notification to action should be "Contact TP" 
Step2: When TP clicks "Withdraw" button the TS status remains "Withdraw intention" and Notification to action should change to "Withdraw TP"

**Comment by klivit** [comment]
@Ana-ui @Mastaleru @cosmintuca Based on the discussion with the business, there is no need from the patient side to have withdraw and withdraw intention (both). Please also check issue #328.
Point 1 - patient cannot withdraw themselves. Point 2 - Once patient decided to withdraw (i.e., "clicked" withdraw intention), the HP should receive a message and will talk to them in-person. This is happening always this way (e.g., HP talks to a TP, ensuring the motivation to withdraw remains, and once it is confirmed, the SITE withdraws the TP). In case more elaborations needed, please let me know.

**Comment by Ana-ui** [comment]
Thank you for the clarification! This is how is planned to be implemented. The Site will withdraw the pacient from the trial. We decide to keep the "Withdraw" button on the TP SSApp just to be covered from the legal perspective so that the patient can anytime request to be withdrawn even if the withdrawn will be done by the doctor

**Comment by klivit** [comment]
@Ana-ui @cosmintuca @Mastaleru Just to make sure we are all on the same page as I've just spoken to Baldwin. We keep **only** "Withdraw" in TP UI (#328 was updated with the word "CHANGE!!!" indicating the update). When TP clicks "Withdraw", it will trigger the status in the system "Withdraw Intention". Please check #328 as it was confirmed by the business as well as this issue. Please note that there is no "Withdrawed" but "Withdrawn".

**Comment by Ana-ui** [comment]
The decision with 2 buttons was decided and agreed in an extended business meeting. Let‘s meet and discuss!

**Comment by klivit** [comment]
As it was finally confirmed by the business leads of the UC, TP has only "Withdraw" (no "Withdraw Intention") to avoid TP's misunderstanding. "Withdraw Intention" will be a status in the SITE SSApp once the TP decides to withdraw. Please check also #328.

**Comment by Ana-ui** [comment]
Hi Kristina,
There is an open document under discussion for business clarifications.
Please have a look at it and add your comments where needed.
https://docs.google.com/document/d/1Fr9Vgye4-xSNplD-HFLyFW4bd7nNQHZgL3TnbUA4eSg/edit?usp=sharing
Best,
Ana
------------------------
Ana Maria Balan, PhD

Telephone: +40 799 881 171
Email: ***@***.***

**Comment by klivit** [comment]
This issue is an existing one for over a week. Hence, I fulfill it with new details requested by the core devs regarding the issue that I opened. I would highly recommend to incorporate in the proposed doc the new issues so you could undertake a lead there (on the points that you have raised/clarified with the business).

This specific requirement can be considered finalized as the decision/request is coming from the leads of the business UC.

**Comment by Mastaleru** [comment]
![image](https://user-images.githubusercontent.com/1469129/189687325-b26544cb-04f4-4058-8fea-7a49c2e3f858.png)
