### ISSUE TITLE
[SITE] TP screen failed and discontinuing process

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#330]
**VALID FOR THE 1ST VERSION OF THE MANDATORY CONSENT**

If a TP signs a consent, but the SITE declines it, the TP will be **automatically** given with the status "**Screen Failed**".
If a TP declines a consent, the TP will be **automatically** given with the status "**Screen Failed**".
However, we keep "Screen Failed" as well for manual (SITE) as it can be changed by the SITE at other steps of the process.

Related issue: #329

![Screenshot 2022-08-05 at 3 13 15 PM](https://user-images.githubusercontent.com/77613409/183075109-0fb68120-6415-4509-acf7-f7040f0feedc.png)

**VALID FOR 2ND (and so on) VERSION OF THE MANDATORY CONSENT**

If a TP signs a consent, but the SITE declines it, the TP will be **automatically** "**Discontinued**" from the study.

<img width="1204" alt="Screenshot 2022-08-03 at 3 46 44 PM" src="https://user-images.githubusercontent.com/77613409/182613722-761c6699-ef53-44e7-9463-aebc80a5dde6.png">

<img width="1205" alt="Screenshot 2022-08-03 at 3 47 05 PM" src="https://user-images.githubusercontent.com/77613409/182614623-07d7e427-2d48-4b66-91b5-c2fdad7b2e24.png">

**Comment by Mastaleru** [comment]
@klivit, I'm not getting why the version of mandatory consent cause different TP statuses. Did you refer to different consents?

**Comment by klivit** [comment]
@Mastaleru When we have a 2nd (and so on) version of the consent, the happy path is that it goes through the same process (i.e., TP signs, SITE signs, etc.). However, the SITE might discontinue the TP from the trial (in cases the patient is not compliant, etc.), which can generally happen during the trial (this is why we leave the "Discontinued" TS status that can be changed by SITE manually), but it can also be triggered by the SITE declining the consent. So, decline consent (by SITE) = Discontinued [TP].

When the SITE declines the original/first consent, it will trigger a "Screen Failed" status (so the TP is out of the trial).

Please let me know if more elaboration is needed.

**Comment by Mastaleru** [comment]
Thank you. Make sense for me now.

**Comment by klivit** [comment]
Related issue (TP status): #329
