### ISSUE TITLE
[SITE] TP number modification details

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#331]
Usually, the TC number should not be modified. This issue is not critical to be done before the mock trial; hence, I added a "future" label.

<img width="1204" alt="Screenshot 2022-08-03 at 4 11 51 PM" src="https://user-images.githubusercontent.com/77613409/182617513-5be30b8e-6b62-49c3-a8f3-e3831ac90d6e.png">

**Comment by Mastaleru** [comment]
I don't know.  What happens if SITE inputs a wrong TS number(e.g typo) and they want to modify it? I would like to keep this feature in order to fix possible human errors. A wrong TS number will mismatch health data from iot-adapter

**Comment by klivit** [comment]
@Mastaleru Your logic is clear to me as I followed the same way of thinking (e.g., we have a chance to fix a mistake). However, as was described by the business, this is not used in real practice (e.g., the TP number should not be altered). And in case the SSApp is originating/generating the TP number, the modification won't be needed. So I left it as "future" as we might dig deeper into the need, but not at this stage of the development.

**Comment by Mastaleru** [comment]
> And in case the SSApp is originating/generating the TP number, the modification won't be needed.

TS number is provided by external platforms with which we don't have any integration yet.
