### ISSUE TITLE
[SITE] Automated visits & procedures scheduling

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#333]
Related issue regarding V0: #332 

In the future, the business would expect all scheduling to be autogenerated based on the V0. The functionality re-schedule shall be available (as it is now).

<img width="1203" alt="Screenshot 2022-08-03 at 5 36 01 PM" src="https://user-images.githubusercontent.com/77613409/182635763-9dbca435-c846-466d-b215-71dea9b42215.png">

**Comment by Mastaleru** [comment]
@klivit the visits has possible ranges. I think this should be performed manually according with SITE availability

**Comment by klivit** [comment]
@Mastaleru This is a future issue (most likely after the PL). The business clearly expressed the vision that scheduling (ideally) shall be automatic (within the ranges and working hours, of course). If the scheduling is not convenient (to a SITE), the SITE has a chance to reschedule. However, it is expected that the original scheduling should be autogenerated (again, in the future). I assume it might also deal with the number of patients and avoid overlapping appointments (e.g., imagine we have 50 patients in the same trial for the same site). The autogeneration of schedules will help to avoid/minimize inconsistencies in booking and allow the SITE to avoid notifications like "This time is already booked". Additionally, I believe we will ahem to encounter the duration of the procedure/visit.
