### ISSUE TITLE
[SITE] Should not be able to add participants with a date of birth that did not happen

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#334]
SITE should not be able to add future dates for the date of birth of TP. 

<img width="402" alt="Screenshot 2022-08-03 at 5 57 24 PM" src="https://user-images.githubusercontent.com/77613409/182640930-3ffbe153-fca9-41b3-b707-7ee94af2dbb5.png">

**Comment by Mastaleru** [comment]
@cosmintuca let's add a minimum date of January 1900. 
![image](https://user-images.githubusercontent.com/1469129/183015683-756b2dd7-8853-4707-b175-3b8225eeda5f.png)

**Comment by cosmintuca** [comment]
@Mastaleru I made the requested changes in this commit: https://github.com/PharmaLedger-IMI/clinical-site-ssapp/commit/16e6c121203ab0f5c77fb5bd121c846d83e906a5

**Comment by Mastaleru** [comment]
the min/max date should be populated direct from model in getInitModel

**Comment by Mastaleru** [comment]
and there you could write directly `min='1900-01-01'`

**Comment by Mastaleru** [comment]
and `max = momentService(Date.now()).format(Constants.DATE_UTILS.FORMATS.YearMonthPattern)`

**Comment by Mastaleru** [comment]
all good now
