### ISSUE TITLE
[SITE] Should not be able to add past dates when scheduling visits & procedures

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#335]
SITE should not be able to add past dates when scheduling.

![Screenshot 2022-08-03 at 6 05 53 PM](https://user-images.githubusercontent.com/77613409/182645051-d4a544da-f1f4-43a3-8933-6406a5975477.png)

**Comment by Mastaleru** [comment]
@cosmintuca this should be performed only for first visit. the intervals remains as they are now.

**Comment by Mastaleru** [comment]
all good
