### ISSUE TITLE
[TP] Invitations can be accepted/declined/rescheduled for 2nd time the action is requested

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#336]
It takes to make each accept/decline/reschedule two times before the system responds.

![Screenshot 2022-08-03 at 6 22 14 PM](https://user-images.githubusercontent.com/77613409/182647036-4d755b45-e87a-4a00-9100-4c88f67eab9e.png)

**Comment by Mastaleru** [comment]
I confirm that happens to me on non development deployments

**Comment by Mastaleru** [comment]
all good
