### ISSUE TITLE
[TP] Calendar and Invitations might be considered for slight rearrangement

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#337]
During the testing, it was not easy/straight forward to understand a common screen/space for the "Calendar" and "Invitations". In the future, these two entities might be considered to be re-organized. 

<img width="310" alt="Screenshot 2022-08-03 at 5 47 48 PM" src="https://user-images.githubusercontent.com/77613409/182787128-ed205fda-c33a-47af-9aea-3304d2d44f21.png">

Please note that I do not add more details here as it needs further investigations/studying, and given the fact that this issue is to be considered after PL, we do not have to work on it at this point. I keep it for the record.

**Comment by Mastaleru** [comment]
current implementation 
![image](https://user-images.githubusercontent.com/1469129/186708234-ba7b6daf-fee9-4fc9-b90c-9b574e495a9d.png)
