### ISSUE TITLE
[SITE] Notifications list to be improved

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#339]
![Screenshot 2022-08-04 at 10 47 51 AM](https://user-images.githubusercontent.com/77613409/182793264-f2c2b60e-b789-4a3a-9174-f1a7e42b38e4.png)

![Screenshot 2022-07-29 at 2 12 22 PM](https://user-images.githubusercontent.com/77613409/182849528-61eaf03d-2de2-43f5-9ea9-75b3b3e02ffd.png)

Please note that I do not add more details here as it needs further investigations/studying, and given the fact that this issue is to be considered after PL, we do not have to work on it at this point. I keep it for the record.

**Comment by Mastaleru** [comment]
![image](https://user-images.githubusercontent.com/1469129/193312544-5cac9ee9-f35f-43be-935a-beec89ef4c7d.png)
![image](https://user-images.githubusercontent.com/1469129/193312576-a9914766-d307-4769-8ad4-37e9f9b7d5e0.png)
![image](https://user-images.githubusercontent.com/1469129/193312608-63cc9300-2894-482c-8258-5e34af613a7b.png)
