### ISSUE TITLE
[TP] New consent is placed under a different trial

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#340]
TP receives a notification about new consent and follows it. 

<img width="314" alt="Screenshot 2022-08-04 at 12 49 17 PM" src="https://user-images.githubusercontent.com/77613409/182818689-a86545ce-79b4-435f-ad5a-354b42ea14d4.png">

TP has info of another consent, and the new consent is listed under a different study.

<img width="303" alt="Screenshot 2022-08-04 at 12 49 38 PM" src="https://user-images.githubusercontent.com/77613409/182819044-339f48bb-c6f7-48fb-b71a-c8cb45991109.png">

We might consider having a separate page called "Trials", where a patient can select a trial and under each trial, they will see the list of consents per this specific trial (mandatory, versions of mandatory, optional, etc.).

**Comment by Mastaleru** [comment]
@klivit This functionality will be implemented in the future in the Past Trials. For the moment (mock-trial) I implemented #374 which will guarantee that no other trials and messages from another trials will be consumed by the patient.
