### ISSUE TITLE
[SITE] [SPO] [TP] Inconsistencies between the TP statuses in different pages/SSApps (TO BE UPDATED)

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#341]
@Mastaleru This issue is a work in progress, I will try to cross check the rest of the statuses and add more info here in case I will notice the same. 

**n1** - SITE

<img width="1177" alt="Screenshot 2022-08-04 at 1 07 13 PM" src="https://user-images.githubusercontent.com/77613409/182822025-c9af6ced-5d8c-4b99-b649-f6466a329975.png">

<img width="1177" alt="Screenshot 2022-08-04 at 1 07 23 PM" src="https://user-images.githubusercontent.com/77613409/182822087-7126cc5d-31da-45a7-a5e9-4e85d81938e3.png">

**n2** - SITE, SPO, TP

<img width="313" alt="Screenshot 2022-08-04 at 1 31 41 PM" src="https://user-images.githubusercontent.com/77613409/182826483-52cc64bc-24f3-4a6e-9456-bf16e25d712c.png">

<img width="1176" alt="Screenshot 2022-08-04 at 1 31 29 PM" src="https://user-images.githubusercontent.com/77613409/182826477-24cd55e9-7566-4dfc-9b57-bdb92481997f.png">

<img width="1177" alt="Screenshot 2022-08-04 at 1 31 12 PM" src="https://user-images.githubusercontent.com/77613409/182826469-400d5d90-a660-4faa-8aad-eff594a98484.png">

**n3** - SITE, SPO, TP

TP was discontinued by the SITE.

<img width="1179" alt="Screenshot 2022-08-04 at 2 53 45 PM" src="https://user-images.githubusercontent.com/77613409/182841134-0a1cfb95-be89-4620-8da8-0cd9588ee4cd.png">

But another page of SITE SSApp did not reflect the update. 
 
<img width="1179" alt="Screenshot 2022-08-04 at 2 53 52 PM" src="https://user-images.githubusercontent.com/77613409/182841283-42dba17a-ebb8-4d79-a16c-38c2ee1b5b7c.png">

And other SSApps did not reflect the update as well.

<img width="317" alt="Screenshot 2022-08-04 at 2 54 45 PM" src="https://user-images.githubusercontent.com/77613409/182841452-98f207f7-7802-483f-9cfe-ce8ccf0f8b32.png">

<img width="1178" alt="Screenshot 2022-08-04 at 2 55 00 PM" src="https://user-images.githubusercontent.com/77613409/182841768-a34f5a50-3ce7-4051-9131-c999367114f0.png">

**Comment by Mastaleru** [comment]
those issues were addressed in previous smaller tasks (depending on the action), and almost all of them were already completed
