### ISSUE TITLE
[SITE] No info/visibility that TP signed the consent

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#342]
This is the case when one particular TP got into two trials. 

TP signed the consent.

<img width="312" alt="Screenshot 2022-08-04 at 1 19 29 PM" src="https://user-images.githubusercontent.com/77613409/182829200-87821e4d-d956-4c20-98f0-e626a9eb19f1.png">

It is not shown as signed the level of SITE.

<img width="1176" alt="Screenshot 2022-08-04 at 1 19 38 PM" src="https://user-images.githubusercontent.com/77613409/182829272-80fcaba4-89fd-4f8f-9c1b-43ced0aad164.png">

**Comment by Mastaleru** [comment]
Patient should not be able to participate in the same time in 2 trials: for mock trial we fixed this in #374 
in clinical site patients will be marked as **Unavailable** if they are already enrolled in another trial.

![image](https://user-images.githubusercontent.com/1469129/185148382-96564715-0d7b-4214-9481-59633220bf85.png)

Access to Consents | Answers will be limited
