### ISSUE TITLE
[SITE] Adjusting appointment statuses for both TP and SITE (Proposal)

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#344]
Ts Acceptance -> Appointment Status ("Appointment" can be replaced with something more suitable) -- It will be a general status for the appointment, not only TS-focused but valid for both TS/TP and SITE.
Required -> Scheduled -- Because it is already scheduled.

<img width="1098" alt="Screenshot 2022-08-04 at 3 10 18 PM" src="https://user-images.githubusercontent.com/77613409/182845946-a20b19f3-6d81-4819-94bc-45969b35df61.png">

Agreed [by TS] -> Confirmed (in blue) / Once confirmed by SITE -> Confirmed (in green)
Declined: Once rescheduled -> Rescheduled
Rescheduled: Once confirmed by SITE -> Confirmed

<img width="1090" alt="Screenshot 2022-08-04 at 3 23 45 PM" src="https://user-images.githubusercontent.com/77613409/182846122-a770589b-e910-4061-a727-587bb56aff86.png">

**Comment by Mastaleru** [comment]
all good
