### ISSUE TITLE
[SITE] [Questionnaire] Edit Questions using the same add question modal.

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#348]

**Comment by Mastaleru** [comment]
@cosmintuca cleanup the old pages after implementing edit in modal

**Comment by cosmintuca** [comment]
@Mastaleru I forgot to add the link in commit message: https://github.com/PharmaLedger-IMI/clinical-site-ssapp/commit/3a0cabc6e7c42ba7ada1775ce01b183b9a18a8fa

**Comment by Mastaleru** [comment]
AddQuestionController and EditQuestionController should become one single controller (AddOrEditQuestionController) in order to avoid 99% code duplication

**Comment by Mastaleru** [comment]
all good now
