### ISSUE TITLE
[Site] Notifications page : formulation correction required "New econsent was added" instead of "ecosent".

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#350]

**Comment by Mastaleru** [comment]
@cosmintuca please refactor this typo also in code: services name and variables
![image](https://user-images.githubusercontent.com/1469129/183921293-bdcaa079-47d8-4ba3-9bc3-98c634a08369.png)

**Comment by Mastaleru** [comment]
all good
