### ISSUE TITLE
Use BreadcrumbManager in researcher ssapp as we already use it in clinical-site ssapp

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#354]
get rid of the BreadcrumbNavigatorController usages

**Comment by Mastaleru** [comment]
@cosmintuca in edit study the breacrumb is missing 
![image](https://user-images.githubusercontent.com/1469129/183452591-389efef5-520f-4a2e-871c-ab5a75ed7f56.png)

**Comment by cosmintuca** [comment]
@Mastaleru I added the breadcrumb in the edit page now

**Comment by Mastaleru** [comment]
all good now
