### ISSUE TITLE
[SPO] Trial statuses outline and rules

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#355]
<img width="1062" alt="Screenshot 2022-08-05 at 10 03 36 PM" src="https://user-images.githubusercontent.com/77613409/183144303-c6607b82-b9c1-40d9-b116-4759518f216a.png">

**Latest update**: Once "Cancelled", cannot be back to "Active" or "On Hold".

**Comment by klivit** [comment]
@Mastaleru These are clarifications regarding trial statuses added/modified by SPONSOR.

**Comment by Mastaleru** [comment]
@paiusCatalin avoid setting redundant statuses. e.g if the status is Active it should not be changed to Active again.
![image](https://user-images.githubusercontent.com/1469129/183399429-385aa276-b578-46a8-ab49-bedc7e38430e.png)

**Comment by klivit** [comment]
@Mastaleru I share your vision. Let me clarify with the business for such a modification (and to align on the reason if not). I will keep you updated and in the loop.

**Comment by klivit** [comment]
@Mastaleru It was confirmed by Achal that once the trial is cancelled, there is no need to place it on hold or make it active again. Thanks for raising this point! So, once the trial is cancelled, the TP can get into another trial. Regarding the "On Hold", the details are coming.

**Comment by klivit** [comment]
@Mastaleru Baldwin did a fantastic job by clarifying the details. I am just citing below.

"For our pilot and for simplicity, I would recommend the following:

“On Hold”= stop recruitment of new TPs.  Collection of data from all TPs enrolled in the trial to continue [_Comment from Kristina: collection of data = continue visits & procedures_]. TPs remain active in the trial. Status can be reverted to “Active” or moved to “Cancelled”

“Cancelled”= Stop recruitment of new TPs and stop collection of data from all TPs enrolled in the trial [_Comment from Kristina: stop collection of data = stop visits & procedures_]. TPs to be discontinued. Status cannot be reverted to “Active”"

In reality, the situation will be more complex with the "Cancelled", but Baldwin suggested to simplify it (above is a simplified version) at this stage of the development.

**Comment by Mastaleru** [comment]
completed in https://github.com/PharmaLedger-IMI/eco-sponsor-ssapp/commit/0792479d6012c5770c6ae03a74c20a0e16ed8437
