### ISSUE TITLE
[Patient App] Health Studies UI improvements 

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#360]
The Health Studies pages are not really mobile friendly right. The data is too crowded in a regular tables

**Comment by Mastaleru** [comment]
![image](https://user-images.githubusercontent.com/1469129/183631932-575a923b-8cfd-404c-b4f1-51d1ee0ac6d1.png)

**Comment by Mastaleru** [comment]
![image](https://user-images.githubusercontent.com/1469129/183631967-f078db31-25ab-487b-be88-9ea4c5bd1462.png)

**Comment by Mastaleru** [comment]
![image](https://user-images.githubusercontent.com/1469129/183632062-cdc881d4-3979-469c-a3d7-2dde665425d7.png)

**Comment by Mastaleru** [comment]
Great work!
Some comments
![image](https://user-images.githubusercontent.com/1469129/189210256-53b8909a-cd57-444e-9aff-9404c062c54c.png)
![image](https://user-images.githubusercontent.com/1469129/189210455-db1c3880-7103-4c20-bf55-5e3605414980.png)
Let's put Reject with red
![image](https://user-images.githubusercontent.com/1469129/189210564-76a7f939-0124-438c-ac47-04d31985427c.png)
![image](https://user-images.githubusercontent.com/1469129/189210904-34bbcec1-1b1c-4c87-9547-c6d01733f33b.png)
missing badges
![image](https://user-images.githubusercontent.com/1469129/189212211-f9a9f98d-bc51-4b16-b507-a12286fb8b4f.png)

the permission appears twice after I revoked it.(as being active and revoked)

**Comment by cosmintuca** [comment]
@Mastaleru https://github.com/PharmaLedger-IMI/trial-participant-ssapp/commit/3c7674a262b246380f90a630d5d5f5971757a09d
