### ISSUE TITLE
[Clinical Site] [Recruitment period] Add custom labels for recruitment period

### ISSUE THREAD

**Issue by paiusCatalin** [PharmaLedger-IMI/eco-iot-pmed-workspace#366]
According to the timeline of the recruitment period, add the following labels below recruitment period:

- State: _Recruitment period has not yet started_ - Label: _Not yet recruiting_;
- State: _Recruitment period in progress_ - Label: _Recruiting_;
- State: _Recruitment period has ended_ - Label: _Active, not recruiting_.

**Comment by Mastaleru** [comment]
kinda confusing the last status. why just we don't show the state itself?

**Comment by paiusCatalin** [comment]
These label came from the business clarification document, apparently this is a common terminology for trials. 
https://docs.google.com/document/d/1Fr9Vgye4-xSNplD-HFLyFW4bd7nNQHZgL3TnbUA4eSg/edit?disco=AAAAeuoOm2c
