### ISSUE TITLE
[SITE] Reimplement notifications list using data-for

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#405]
just to avoid code like this

![image](https://user-images.githubusercontent.com/1469129/185930984-76c81563-60c0-4f59-a530-77b0180e50f5.png)

**Comment by cosmintuca** [comment]
@Mastaleru https://github.com/PharmaLedger-IMI/clinical-site-ssapp/commit/90c601adac82b48f3f408bad7dd86f0b4fa79478
