### ISSUE TITLE
Inconsistent usage of ConsentStatusMapper 

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#406]
for the signing it is used "signed" for operation and "sign" for status while for declining it is used the ConsentStatusMapper

![image](https://user-images.githubusercontent.com/1469129/185962761-4631430b-c03e-4770-85f2-77fb5524a06b.png)

**Comment by cosmintuca** [comment]
@https://github.com/PharmaLedger-IMI/clinical-site-ssapp/commit/643d08c50e56a3030d603a843150e770afbc07c2
