### ISSUE TITLE
Researcher app is not receiving health data that is added in the patient healthdsu after he join the study

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#411]

**Comment by Mastaleru** [comment]
@nliappas is this issue valid?

**Comment by nliappas** [comment]
I don't think so, I never experienced such issue.

**Comment by Mastaleru** [comment]
I tested again with one patient and I could reproduce:
3 devices were added to patient prior of being invited in the study
![image](https://user-images.githubusercontent.com/1469129/190687442-599cc124-ccae-46e6-841d-8b8800b97397.png)
last device was added after the patient joined the study (when study status was active)

in the patient app I have 4 records
![image](https://user-images.githubusercontent.com/1469129/190687817-1c45c43b-fe7a-4c47-a98a-d592f56f35c0.png)

In finalized and closed the study:
in the available data I have only 3 records.
![image](https://user-images.githubusercontent.com/1469129/190688063-623de45a-30b1-46ca-8691-c7c07622cbb7.png)

**Comment by Mastaleru** [comment]
@nliappas, just remember that in the pilot, the data will come in a continuous flow.

**Comment by Mastaleru** [comment]
changed the behavior in iot-adapter by updating the existing healthdata DSUs

**Comment by Mastaleru** [comment]
@nliappas I think we should fix this now while the date is collected when the study is completed
