### ISSUE TITLE
Fix on sponsor participant consents and history

### ISSUE THREAD

**Issue by Desouler** [PharmaLedger-IMI/eco-iot-pmed-workspace#414]

**Comment by Desouler** [comment]
Commited @Mastaleru

**Comment by Desouler** [comment]
Close this or i need to do something more?

**Comment by Mastaleru** [comment]
let's make the ifcs to work again as I explained today

**Comment by Desouler** [comment]
commited

**Comment by Mastaleru** [comment]
all good, some minor changes will be added in a separate issue
