### ISSUE TITLE
Wrong history version presented

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#422]
I have 3 consents
![image](https://user-images.githubusercontent.com/1469129/186715629-b0693f1e-fa5c-4bda-807d-10cbce70d94a.png)
I want to check the 3rd one history.

I see history for the first consent

![image](https://user-images.githubusercontent.com/1469129/186715722-a717432d-41d6-4385-935f-8b37bd0c4e27.png)

**Comment by Desouler** [comment]
Comitted

**Comment by Mastaleru** [comment]
all good
