### ISSUE TITLE
[SITE] Consent Preview is not working just after the sponsor ads the SITE to trial

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#423]
Consents has more than one version
After refresh it is working.
@paiusCatalin _this.HCOService.refreshSite_ is no longer proper working?
![image](https://user-images.githubusercontent.com/1469129/186716740-a10e1dab-9e6b-4185-9231-4480ea932251.png)

**Comment by Desouler** [comment]
Commited

**Comment by Mastaleru** [comment]
nothing was fixed in Clinical Site, maybe the issue was from Sponsor? could not reproduce it anymore.... I will close this in several days if I will not be able to reproduce it.

**Comment by Mastaleru** [comment]
I can no longer reproduce it
