### ISSUE TITLE
Invalid date for recruitment period.

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#424]
![image](https://user-images.githubusercontent.com/1469129/186719064-16a32829-6f84-4eb5-8541-8d639dcfcb80.png)

Disable Done button when the dates are not valid
![image](https://user-images.githubusercontent.com/1469129/186718983-2fcb002f-9140-4690-9274-fc23b47ba74c.png)

**Comment by Desouler** [comment]
Commited

**Comment by Mastaleru** [comment]
all good
