### ISSUE TITLE
[SPONSOR] Patient status improvements

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#439]
1. Remove TP number from breadcrumb
2. Use Yes/No instead of Booleans
3. Add Enrolled Date
4. Show participant DID (anonymized) and TP number (if available)

![image](https://user-images.githubusercontent.com/1469129/188166781-84c3c983-dac1-4641-89fd-040a2b445283.png)

**Comment by Desouler** [comment]
Commited, i am showing TP number (if available) OR Did (cause TP number unavailable) because both are really too long to show them at the same time

**Comment by Mastaleru** [comment]
> Commited, i am showing TP number (if available) OR Did (cause TP number unavailable) because both are really too long to show them at the same time

agree
