### ISSUE TITLE
[SPONSOR] Patient has status Enrolled, but enrolled Date is missing

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#440]
![image](https://user-images.githubusercontent.com/1469129/188167137-a8734135-9966-44c3-b7ac-7e163fd294f2.png)

**Comment by Mastaleru** [comment]
also, the enrollment percentage should not be 100%, right?

**Comment by Desouler** [comment]
commited
