### ISSUE TITLE
Answers were not updated. new ones were just added. 

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#445]
after I responded the first time,  on the second try, the questionnaire was not filled with details from previous set of responses.
The third time it was.

![image](https://user-images.githubusercontent.com/1469129/188490912-e556ce08-97d8-4546-94f5-f6474e579148.png)

**Comment by cosmintuca** [comment]
@Mastaleru I've tested this behaviour on local dev and deployment and I couldn't replicate this bug. (I've responded to the questionnaire for 3 times in a row and every time I checked the answers in clinical site for that specific TP it worked)

**Comment by Mastaleru** [comment]
@cosmintuca again this issue:)
![image](https://user-images.githubusercontent.com/1469129/192854019-354721b6-30d3-403c-a6d1-50a15dd0b4ca.png)

**Comment by Mastaleru** [comment]
test them with free text and let some empty responses
