### ISSUE TITLE
Improve visits details page

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#446]
![image](https://user-images.githubusercontent.com/1469129/188492299-c854d407-8268-4b1e-91c7-2b99d4754a80.png)
1. **Other visits scheduled** should be chronological sorted.
2. Statuses are not properly displayed.
This is what I have for SITE 

![image](https://user-images.githubusercontent.com/1469129/188492570-70d1d336-72e2-4932-b2b4-40fcbbecc4c0.png)

**Comment by Mastaleru** [comment]
Implement it using webc-switch component

**Comment by Mastaleru** [comment]
@cosmintuca what about declined status?

**Comment by cosmintuca** [comment]
@Mastaleru there's no need to handle the declined status because we only show the scheduled visits
