### ISSUE TITLE
Add Site DID validation

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#456]
Check the site DID before submission
![image](https://user-images.githubusercontent.com/1469129/189132549-f046f928-281c-42f5-b8ee-901cf64e0376.png)
Validate it as we already do this on SITE for patients

**Comment by Desouler** [comment]
commited

**Comment by Mastaleru** [comment]
@Desouler did you pushed?

**Comment by Desouler** [comment]
i commited, did not push, and deleted/created the workspace afterwards. 3rd time i do this :S. None the less did this again, and pushed

**Comment by Mastaleru** [comment]
all good
