### ISSUE TITLE
Search is not working for sites 

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#457]
![image](https://user-images.githubusercontent.com/1469129/189134565-9907cfe5-fbd8-43ed-81a6-8d98ef5dc107.png)

**Comment by Desouler** [comment]
Commited

**Comment by Mastaleru** [comment]
@Desouler Improvement: let's also search by site DID please.

so the palceholder of the search will be Search by Site name or Site DID

**Comment by Desouler** [comment]
Committed

**Comment by Mastaleru** [comment]
all good
