### ISSUE TITLE
add favicons to all ssapps

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#458]
sponsor - >pharma pill
patient -> human profile
researcher -> tube
clinical-site-> hospital

**Comment by Mastaleru** [comment]
@cosmintuca 
![image](https://user-images.githubusercontent.com/1469129/198542027-81a2210f-1b53-4999-8fe2-584bac263b1b.png)

white favicons?
use #008798 icons color

**Comment by cosmintuca** [comment]
@Mastaleru as we discussed on friday, the colour that we want for the favicons is rgba(6, 207, 175, 1). Currently I replaced all the favicons in order to meet this colour
