### ISSUE TITLE
Edit Contact Bug and one improevement

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#460]
When I try to edit contact

![image](https://user-images.githubusercontent.com/1469129/189303902-d45b758d-3b81-487e-af80-cb7310897446.png)

Improvement: Now we don;t display the did of the site, and sometimes it may be required to see it (human purposes)

Let's add here, before the current input (HealthCare Professional Name ) another input that is disabled and presents the did of the site.
.e.g

![image](https://user-images.githubusercontent.com/1469129/189304982-fab6ee88-6c99-4fe2-8938-fcef5945618c.png)

**Comment by Desouler** [comment]
I cannot replicate, it works for me. Any idea about the env at that time?
