### ISSUE TITLE
I should not be able to edit this fields while some patients may already gave their consent to participate - Send study after status is Active.

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#477]
The status of the study is **Approved**.
You should not be able to change sex, age, type of data
![image](https://user-images.githubusercontent.com/1469129/190679055-a5dc43e7-069e-4ddc-85a9-05f29fb26463.png)

OR, maybe the invitations should be sent after changing the status of the study to **Active**.
@nliappas please talk with your team in order to find the best approach.

**Comment by nliappas** [comment]
the invitations should be visible after changing the status of the study to Active
