### ISSUE TITLE
Add Edit button in the Option list of the  Sponsor SSApp

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#478]
Implement Edit function in order to be able to modify the name and Id of a added trial

**Comment by Desouler** [comment]
committed

**Comment by Mastaleru** [comment]
@Desouler : where are the validations?
I should not be able to update the Trial Number id with an existing one
I should not be able to input blank details
![image](https://user-images.githubusercontent.com/1469129/191934231-3a0adc01-4d87-409c-80d1-7a235ce098c9.png)
