### ISSUE TITLE
do not allow to add TP number if the patient status is changed to discontinued or withdrawn 

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#479]
NOTE: if I change a subject status from "planned" to "Discontinued" or "withdrawn" and the system allows me to assign a TP number and a device

**Comment by Mastaleru** [comment]
@Ana-ui the tp number should also no be changed if the status is unavailable or completed.

**Comment by Mastaleru** [comment]
use arrays functions .eg. indexOf, includes
