### ISSUE TITLE
Declined visit by patient appears accepted in patient's calendar

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#487]

**Comment by Mastaleru** [comment]
Steps to reproduce
1. Site schedule visit V3
2. Patient accept visit V3
3. Site reschedule visit V3
4. Patient decline visit V3

**Comment by Mastaleru** [comment]
Another buggy scenario
1. Site schedule visit V3
2. Patient reschedule visit V3 from invitation
3. Site confirm the rescheduled visit V3
4. The visit does not appear in patient app

**Comment by Mastaleru** [comment]
all good
