### ISSUE TITLE
Reschedule button for patients

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#497]
In case of a agreed visit, only the Site can initiate re-scheduling, it would be great if the TP could initiate re-schedulling too

**Comment by Mastaleru** [comment]
error I have on clinical site when I receive the reschedule message from tp
![image](https://user-images.githubusercontent.com/1469129/193311460-3daebfc8-4d32-454e-842f-81d9016f1df2.png)

**Comment by Mastaleru** [comment]
It is working now, but the patient does not have a feedback, that he demanded a reschedule
