### ISSUE TITLE
The Visit procedures appear not in line with the uploaded file. 

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#498]

**Comment by cosmintuca** [comment]
I verified the visits&procedures in all three ssapps and it seems to be synchronized.

**Comment by Mastaleru** [comment]
already fixed
![image](https://user-images.githubusercontent.com/1469129/192849372-f43c46c9-82f4-4145-a68f-b6625ba10bd0.png)
