### ISSUE TITLE
Visit status 

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#499]
In the Visits & Procedures window it would be very useful to see not only the Appointment status, but the Visit status (completed, incomplete, ongoing, late/not done in red

**Comment by Mastaleru** [comment]
@cosmintuca let's discuss this with @Ana-ui

**Comment by Mastaleru** [comment]
New  column before of  Visits-> Status
All Completed -> green icon (fa-check-circle)
Partial Completed -> orange icon (fa-circle-o-notch)
Missed -> red icon (fa-times-circle)

Only after the doctor confirmed attendance

**Comment by Mastaleru** [comment]
if no status is available we should display N/A
