### ISSUE TITLE
Correct questionnaire notification

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#503]
Once HCP enrolls the participant, participant receives notifications not only about the trial and consents, but also that a new questionnaire can sent (which is not correct as no questionnaires were sent by HCP at this stage)
The questionnaire DSU is created if you just visit the questionnaire page and it is sent to all enrolled patients even if no question was added.

**Comment by Mastaleru** [comment]
Usually the site should set the questionnaire before the actual patient enrolment.
