### ISSUE TITLE
Implement cursor

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#505]
Would be useful to have the cursos become a "hand" to indicate user that there is an action possible. Right now the cursors stay as is, which can be confusing that the ICFs are there only to be vissualized

**Comment by Mastaleru** [comment]
you don't have cursors in mobile view

**Comment by Mastaleru** [comment]
if the mobile view is not enabled you have the cursor
