### ISSUE TITLE
Preview consent history 

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#506]
On the preview page, "Signed" appears in header and it shows V1 and V2 of consent but participant would've only signed V2. Therefore V1, should not show up. Digital signature only shows up in V2 as it should.

**Comment by Mastaleru** [comment]
@cosmintuca, @Ana-ui is referring to this page
![image](https://user-images.githubusercontent.com/1469129/191782328-82f9a116-978f-4dab-8354-a90741091843.png)

can you also make some improvements using ion lists?
