### ISSUE TITLE
Patient status should appear declined only for mandatory consent 

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#508]
In the HCP/site application my participant / subject status is changed to "decline" even if I declined only the optional Icf, and accepted the mandatory one

**Comment by Ana-ui** [comment]
I accepted Mandatory consent and declined Optional consent. The optional consent automatically showed up as subject had declined across sponsor and site wallets. However, if it's optional, it shouldn't do that. Need to ensure in live trial that optional procedures/documents are treated as such.

**Comment by cosmintuca** [comment]
@Ana-ui for withdrawn similar behaviour to be corrected and not affect the status of the patient

**Comment by Mastaleru** [comment]
@cosmintuca check the commit message
