### ISSUE TITLE
Multiple data for research study

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-iot-pmed-workspace#510]
Can only choose 1 item. May need to make this multi-pick in future

**Comment by Mastaleru** [comment]
@nliappas add all the study data-types on permissions page:
![image](https://user-images.githubusercontent.com/1469129/193324056-440a2ad8-201c-4d8d-9856-79d2069deb84.png)
![image](https://user-images.githubusercontent.com/1469129/193324491-87de00c9-ab7c-4b3a-813b-ba779ebfaf60.png)
