### ISSUE TITLE
After I signed the optional consent I still have notification for action: "Set TP number"

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#518]
Consents signed:
![image](https://user-images.githubusercontent.com/1469129/194041545-c453e1f7-478d-4cee-81e1-fb4860e72b36.png)

![image](https://user-images.githubusercontent.com/1469129/194042162-e8eb3b73-5abf-4dd6-9c31-297fa9b09258.png)

**Comment by Mastaleru** [comment]
@cosmintuca I still have _Set TS Number_ notification for action after HCO declined the  optional consent. Mandatory was already signed and TS number was already set at a previous step.
![image](https://user-images.githubusercontent.com/1469129/195615274-1d0752df-9a58-4ecf-bdc4-2a3e237330b8.png)
![image](https://user-images.githubusercontent.com/1469129/195615526-c08d2638-26d4-423d-a342-8b0592994695.png)

**Comment by cosmintuca** [comment]
@Mastaleru I've tested the case you described above with mandatory signed by both and optional signed by tp and declined by HCO and the notification is : Schedule Visit .

At the time you've tested that case I haven't handled the notification for action when we changed the status of a tp from status page. I've tested with manually changing the statuses and it seems to work fine. In the case you described above, after I set the end of treatment or any other negative status, the notification for action will be 'No action required'
