### ISSUE TITLE
Edit TP status behavior change

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#521]
After I set one of the following statuses to  [Unavailable, Screen Failed, Discontinued,  End of Treatment] I should not be able to change the status again.

**Comment by cosmintuca** [comment]
@Mastaleru @Ana-ui  Should we add also the Completed Status ?

**Comment by Mastaleru** [comment]
@cosmintuca it is working only if I leave the page and come back, the button should become disabled after I set one of the provided statuses.

**Comment by Mastaleru** [comment]
and add a UI loader while you are performing the changes in background
