### ISSUE TITLE
Transform DSUs data in HL7 format

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#530]
DSUs Data Types that need HL7 format:

- trial
- clinical site (site)
- site consent
- inform consent (ifc)
- trial participant (tp)
- visit

**Comment by Mastaleru** [comment]
I attached below the DSUs structures
[dsus-structures.zip](https://github.com/PharmaLedger-IMI/eco-iot-pmed-workspace/files/9776283/dsus-structures.zip)

**Comment by Mastaleru** [comment]
In my opinion you should not touch the ssapps itself. You have to hook the methods from DSUService in order to store the data in HL7 format and to restore data from HL7 format.

**Comment by elubilu** [comment]
TVS will be working on **Trial** and **Clinical Site**  to transform data to HL7 format.

**Comment by nliappas** [comment]
I'm working on the 

- site consent

- inform consent (ifc)

**Comment by Mastaleru** [comment]
@elubilu , @nliappas I hope that HL7TransformationRegistry brings more light on how to avoid changing existing DSU structure.
https://github.com/PharmaLedger-IMI/eco-iot-services/commit/f648190ac20664e5fdb1d8f082054e8c5e0e4e6d
