### ISSUE TITLE
Do not send trial consent notifications to site.

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#532]
There is no reason to send trial consents notifications to site when the site should be notified only about site consents.

Steps to reproduce.
1.Create a trial and add a Site
2.Create a trial consent
3. Site receives a notification: (Trial Updates -> New procedure was added).

I think that you have to make the changes in _AddNewTrialConsentModalController_ .
![image](https://user-images.githubusercontent.com/1469129/195588252-d38798f7-5026-407e-a19a-e2176e9f5a8b.png)

**Comment by Desouler** [comment]
Committed
